#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
source ~/OpenFOAM/OpenFOAM-v2212/etc/bashrc			# source OpenFOAM
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

#------------------------------------------------------------------------------
./Allclean

restore0Dir

runApplication blockMesh

surfaceMeshExtract enclosure.stl
#------------------------------------------------------------------------------
