#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
#--------------------------------------------------------

# preparations
cp -r 0.org 0

# base mesh
runApplication blockMesh
cp ./system/snappyHexMeshDict_1 ./system/snappyHexMeshDict
runApplication snappyHexMesh -overwrite

# cut mesh with symmetryPlane
mv log.snappyHexMesh log.snappyHexMesh1
cp ./system/snappyHexMeshDict_2 ./system/snappyHexMeshDict
runApplication snappyHexMesh -overwrite

# run
runApplication setAlphaField
runApplication decomposePar
mpirun -n 4 interFlow -parallel > log.interFlow


