#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
source ~/.bashrc									# load bashrc to get scaleSTL command
#------------------------------------------------------------------------------
./Allclean

restore0Dir

runApplication blockMesh

surfaceMeshExtract enclosure.stl
#------------------------------------------------------------------------------
