#!/bin/sh
source ~/.bashrc
of2212												# load local OpenFOAM installation V2212

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication surfaceFeatureExtract

runApplication decomposePar -force

#------------------------------------------------------------------------------
