#!/bin/sh
source ~/.bashrc
of2212												# load local OpenFOAM installation V2212

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#restore0Dir

#runApplication blockMesh

#runApplication surfaceFeatureExtract

#runApplication snappyHexMesh -overwrite

#runApplication checkMesh -writeAllFields -latestTime

#runApplication $(getApplication)

#touch post.foam

# reconstruct mesh from all processors - latest time is 2 (no boundary layer step)
runApplication reconstructParMesh -latestTime

# remove all processor folders
rm -r processor*

# copy polyMesh from latestTime folder to constant folder for single core computation 
cp -r 2/polyMesh constant/
rm -r 2

runApplication $(getApplication)

touch post.foam


#------------------------------------------------------------------------------
